name: CI for Next.js Docker App

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout do repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Configura o Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Constrói a imagem Docker
      - name: Build Docker image
        run: docker build . -t devstore

      # Roda os testes do Next.js (se houver)
      - name: Run Tests
        run: docker run devstore npm test

      # Publica a imagem no Docker Hub (opcional)
      # - name: Log in to Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     username: ${{ secrets.DOCKER_USERNAME }}
      #     password: ${{ secrets.DOCKER_PASSWORD }}

      # - name: Push to Docker Hub
      #   run: docker push devstore
